var lang_ES = {
    etiquet: {
        option_ap: 'Opciones de Apariencia',
        cerrar_session: 'Cerrar sesión',
        pantalla_full: 'Maximizar pantalla',
        atajo: 'Atajo',
        proyectos: 'Proyectos',
        proyecto_recuentes: 'Proyectos recientes',
        encabezado_fijo: 'Encabezado Fijo',
        menu_fijo: 'Menú Fijo',
        navegacion_fijo: 'Navegación Fijo',
        footer_fijo: 'Footer Fijo',
        contenido_centrado: 'Contenido Centrado',
        menu_derecha: 'Menú a la <b>Derecha</b>',
        menu_arriba: 'Menú <b>Arriba</b>',
        para_daltonicos: 'Para daltónicos',
        estilos: 'Estilos',
        defecto: 'Defecto',
        oscuro_elegante: 'Oscuro Elegante',
        ultra_claro: 'Ultra Claro',
        anaranjado: 'Anaranjado',
        pixel: 'Pixel',
        trasparente: 'Trasparente',
        celeste: 'Celeste',
        user: 'Usuario',
        pass: 'Contraseña',
        forgot_pass: '¿Olvide mi contraseña?',
        copy_right: '&COPY; 2017 -  Perú. Todos los derechos reservados.',
        btn_entrar: 'Entrar',
        search_menu: 'Buscar menú...',
        inactividad: 'Como ha estado inactivo, su sesión está a punto de caducar.',
        tiempo_inactividad: 'Tiempo restante',
        continuar: 'Continuar',
        salir: 'Salir',
        cierre_sesion: 'Advertencia de cierre de sesión',
        loading: 'Cargando...',
        new_menu: 'Nuevo Menú',
        edit_menu: 'Editar Menú',
        descripcion: 'Descripción',
        press_enter: 'Escriba y presione [Enter]',
        t_alias: 'Este alias se utilizará como prefijo para todos los elementos que serán contenidos en el menú que se creará, debe ser único en el sistema y debe finalizar con dos guiones bajo(__). Se permiten 10 caracteres como máximo.',
        t_ajax: `Evento que se ejecutará al dar click en la opción de menú. Ejm: Exe.load('MODULO','OPCION');`,
        alias: 'Alias',
        ajax: 'Ajax',
        activo: 'Activo',
        btn_close: 'Cerrar',
        btn_agregar: 'Agregar',
        btn_limpiar: 'Limpiar',
        icono: 'Icono',
        css: 'Css',
        new_boton: 'Nuevo Botón',
        edit_boton: 'Editar Botón',
        nombres: 'Nombres',
        nombre: 'Nombre',
        theme: 'Diseño',
        estado: 'Estado',
        ant: 'Ant',
        sig: 'Sig',
        fin: 'Finalizar',
        tour: 'Tour',
        e_si: 'Si',
        e_no: 'No',
        new_rol: 'Nuevo Rol',
        edit_rol: 'Editar Rol',
        rol_access: 'Accesos para: <span></span>',
        search_sensitive: 'Escriba para buscar...',
        rol: 'Rol',
        preview: 'Vista Previa',
        new_categoria: 'Nueva Categoría',
        edit_categoria: 'Editar Categoría',
        visualizar: 'Visualizar',
        imagen: 'Imagen',
        meta_titulo: 'Meta Título',
        meta_descripcion: 'Meta Descripción',
        meta_keywords: 'Meta Keywords',
        tagsinput_ph: 'Escribe y presiona enter.',
        caterorias: 'Categorías',
        informacion_general: 'Información General',
        configuracion: 'Configuración',
        productos: 'Productos',
        principal: 'Principal',
        modo_vista: 'Modo vista',
        categoria: 'Categoría',
        producto: 'Producto',
        categoria_visible_para: 'Categoría visible para',
        visitante: 'Visitante',
        cliente: 'Cliente',
        registrar_producto: 'Rregistrar Producto',
        tags: 'Tags',
        seo: 'SEO',
        stock_minimo: 'Stock Mínimo',
        stock: 'Stock',
        precio_venta: 'Precio Venta',
        caracterisricas: 'Características',
        valor: 'Valor',
        seleccionar: 'Seleccionar',
        todos: 'Todos',
        imagenes: 'Imagenes',
        arrastra_aqui: 'Arrastra los archivos aquí o haz click para cargarlos.',
        error_ulpoad: 'Error al subir el archivo',
        ingrese_valor_caracteristia: 'Ingrese el valor de la característica.',
        seleccione_caracteristica: 'Seleccione una característica.',
        registrar_vehiculo: 'Registrar Vehículo',
        duenio_vehiculo: 'Dueño del Vehiculo',
        apellido_paterno: 'Apellido Paterno',
        apellido_materno: 'Apellido Materno',
        primer_nombre: 'Primer Nombre',
        segundo_nombre: 'Segundo Nombre',
        datos_vehiculo: 'Datos del Vehículo'
    },
    msn: {
        login_ok: 'Ingreso correctamente.',
        login_fail: 'Error con el usuario o contraseña.',
        msn_sys: 'Aviso del sistema:',
        msn_logout: '¿Desea salir: ',
        msn_seguridad_logout: 'Para mayor segurdad cierre el navegador.',
        save_ok: 'Datos se grabaron correctamente.',
        edit_ok: 'Datos se editaron correctamente.',
        delete_ok: 'Registro(s) se eliminó correctamente.',
        you_sure_delete: '¿Está seguro de eliminar el registro?',
        menu_exist: 'Descripción de menú ya existe.',
        alias_exist: 'Alias ya existe.',
        ajax_exist: 'Ajax ya existe.',
        boton_exist: 'Boton ya existe.',
        rol_exist: 'Rol ya existe.',
        copy_ok: 'Registro se duplico correctamente.',
        validate: 'Revise los campos marcados',
        categoria_exist: 'Categoría ya existe.'
    }
};