var lang_ES = {
    etiquet: {
        no_registros: 'No se encontraron registros.',
        option_ap: 'Opciones de Apariencia',
        cerrar_session: 'Cerrar sesión',
        pantalla_full: 'Maximizar pantalla',
        atajo: 'Atajo',
        proyectos: 'Proyectos',
        proyecto_recuentes: 'Proyectos recientes',
        encabezado_fijo: 'Encabezado Fijo',
        menu_fijo: 'Menú Fijo',
        navegacion_fijo: 'Navegación Fijo',
        footer_fijo: 'Footer Fijo',
        contenido_centrado: 'Contenido Centrado',
        menu_derecha: 'Menú a la <b>Derecha</b>',
        menu_arriba: 'Menú <b>Arriba</b>',
        para_daltonicos: 'Para daltónicos',
        estilos: 'Estilos',
        defecto: 'Defecto',
        oscuro_elegante: 'Oscuro Elegante',
        ultra_claro: 'Ultra Claro',
        anaranjado: 'Anaranjado',
        pixel: 'Pixel',
        trasparente: 'Trasparente',
        celeste: 'Celeste',
        user: 'Usuario',
        pass: 'Contraseña',
        forgot_pass: '¿Olvide mi contraseña?',
        copy_right: '&COPY; 2018 -  Perú. Todos los derechos reservados.',
        btn_entrar: 'Entrar',
        search_menu: 'Buscar menú...',
        inactividad: 'Como ha estado inactivo, su sesión está a punto de caducar.',
        tiempo_inactividad: 'Tiempo restante',
        continuar: 'Continuar',
        salir: 'Salir',
        cierre_sesion: 'Advertencia de cierre de sesión',
        loading: 'Cargando...',
        new_menu: 'Nuevo Menú',
        edit_menu: 'Editar Menú',
        descripcion: 'Descripción',
        press_enter: 'Escriba y presione [Enter]',
        t_alias: 'Este alias se utilizará como prefijo para todos los elementos que serán contenidos en el menú que se creará, debe ser único en el sistema y debe finalizar con dos guiones bajo(__). Se permiten 10 caracteres como máximo.',
        t_ajax: `Evento que se ejecutará al dar click en la opción de menú. Ejm: Exe.load('MODULO','OPCION');`,
        alias: 'Alias',
        ajax: 'Ajax',
        activo: 'Activo',
        btn_close: 'Cerrar',
        btn_agregar: 'Agregar',
        btn_limpiar: 'Limpiar',
        icono: 'Icono',
        css: 'Css',
        new_boton: 'Nuevo Botón',
        edit_boton: 'Editar Botón',
        nombres: 'Nombres',
        nombre: 'Nombre',
        theme: 'Diseño',
        estado: 'Estado',
        ant: 'Ant',
        sig: 'Sig',
        fin: 'Finalizar',
        tour: 'Tour',
        e_si: 'Si',
        e_no: 'No',
        new_rol: 'Nuevo Rol',
        edit_rol: 'Editar Rol',
        rol_access: 'Accesos para: <span></span>',
        search_sensitive: 'Escriba para buscar...',
        rol: 'Rol',
        preview: 'Vista Previa',
        new_categoria: 'Nueva Categoría',
        edit_categoria: 'Editar Categoría',
        visualizar: 'Visualizar',
        imagen: 'Imagen',
        meta_titulo: 'Meta Título',
        meta_descripcion: 'Meta Descripción',
        meta_keywords: 'Meta Keywords',
        tagsinput_ph: 'Escribe y presiona enter.',
        caterorias: 'Categorías',
        informacion_general: 'Información General',
        configuracion: 'Configuración',
        productos: 'Productos',
        principal: 'Principal',
        modo_vista: 'Modo vista',
        categoria: 'Categoría',
        producto: 'Producto',
        categoria_visible_para: 'Categoría visible para',
        visitante: 'Visitante',
        cliente: 'Cliente',
        registrar_producto: 'Rregistrar Producto',
        tags: 'Tags',
        seo: 'SEO',
        stock_minimo: 'Stock Mínimo',
        stock: 'Stock',
        precio_venta: 'Precio Venta',
        caracterisricas: 'Características',
        valor: 'Valor',
        seleccionar: 'Seleccionar',
        todos: 'Todos',
        imagenes: 'Imagenes',
        arrastra_aqui: 'Arrastra los archivos aquí o haz click para cargarlos.',
        error_ulpoad: 'Error al subir el archivo',
        ingrese_valor_caracteristia: 'Ingrese el valor de la característica.',
        seleccione_caracteristica: 'Seleccione una característica.',
        registrar_vehiculo: 'Registrar Vehículo',
        duenio_vehiculo: 'Propietario del Vehiculo',
        apellido_paterno: 'Apellido Paterno',
        apellido_materno: 'Apellido Materno',
        primer_nombre: 'Primer Nombre',
        segundo_nombre: 'Segundo Nombre',
        datos_vehiculo: 'Datos del Vehículo',
        pais: 'País (nacionalidad)',
        estado_civil: 'Estado Civil',
        telefono_casa: 'Telefono Casa',
        telefono_trabajo: 'Telefono Trabajo',
        celular: 'Celular',
        direccion_domicilio: 'Dirección de Domicilio',
        direccion_trabajo: 'Dirección de Trabajo',
        tipo_doc: 'Tipo Doc.',
        nro_documento_identidad: 'Nro. de Doc. de Identidad',
        img_doc_identidad: 'Doc. de Identidad (imagen)',
        img_licencia_conducir: 'Licencia de Conducir (imagen)',
        tarjeta_propiedad: 'Tarjeta de Propiedad',
        placa: 'Placa',
        marca: 'Marca',
        modelo: 'Modelo',
        nro_motor: 'Nro. de Motor',
        nro_serie: 'Nro. Serie',
        anio_fabricacion: 'Año de Fabricación',
        cilindrada: 'Cilindrada',
        img_tarjeta_propiedad: 'Tarjeta de Propiedad (imagen)',
        recibo_agua_luz_gas: 'Recibo de Agua/Luz/Gas Natural',
        nro_revision_tecnica: 'Nro. Revisión Técnica',
        fecha_prox_inspeccion: 'Fecha de Próxima Inspección',
        img_revision_tecnica: 'Revisión Técnica (imagen)',
        soat: 'SOAT (número de póliza)',
        fecha_soat: 'Fecha de vigencia de póliza',
        inscripcion_app_movil: 'Inscripcion de app movil (Uber, Easy Taxi)',
        img_soat: 'SOAT (imagen)',
        consentimiento: 'Principio de consentimiento al tratamiento de datos personales del cliente',
        otros_datos: 'Otros Datos',
        aqui: '(aqui)',
        formato_solicitud_cobranza: 'Formato de Solicitud de Cobranza',
        hoja_unica_datos: 'Hoja Única de Datos - Calidda',
        documentos: 'Documentos',
        img_consentimiento: 'Consentimiento (imagen)',
        nro_exp: 'Nro. Exp.',
        pre_conversion: 'Pre Conversión',
        conversion: 'Conversión',
        apellidos_nombres: 'Apellidos y Nombres',
        apellidos: 'Apellidos',
        direccion: 'Dirección',
        inspecciones_visuales: 'Inspecciones Visuales',
        condiciones_chasis: 'Condiciones del Chasis',
        conforme: 'Conforme',
        no_conforme: 'No Conforme',
        estado_carga_control: 'Estado y carga del sistema eléctrico y Verificación del control y estabilidad del sistema de carga',
        bateria: 'Bateria',
        apagado: 'Apagado',
        arranque: 'Arranque',
        ralenti: 'Ralenti',
        voltios: 'Voltios',
        '2500_rpm': '2500&nbsp;RPM',
        masa_motor: 'Masa de Motor',
        masa_chasis: 'Masa de Chasis',
        estado_bateria: 'Estado de Batería',
        botones: 'Botones',
        anclaje: 'Anclaje',
        nivel_electrolito: 'Nivel de Electrolito',
        estado_motor_arranque: 'Estado del Motor de Arranque',
        estado_sistema_carga: 'Estado del Sistema de Carga',
        alternador: 'Alternador',
        correas_alternador: 'Correas de Alternador',
        sistema_encendido: 'Sistema de Encendido',
        numero_invalido: 'Número inválido',
        observaciones: 'Observaciones',
        tipo_sistema_encendido: 'Tipo de Sistema de Encendido',
        estado_admision_aire: 'Estado de Sistema de Admisión de Aire',
        estado_aire_despues_sensor:'Estado de la toma de aire despues del sensor',
        estado_filtro_aire: 'Eestado del filtro de aire',
        observacion: 'Observación',
        rechazar: 'Rechazar',
        panel: 'Panel',
        sistema_conversiones: 'Sistema de Gestión de Conversiones',
        bienvenido: 'Bienvenido',
        grafico_pre_conversion: 'Gráfico de Pre Conversión',
        aprobados: 'Aprobados',
        rechazados: 'Rechazados',
        pendientes: 'Pendientes',
        grafico_conversion: 'Gráfico de Conversión',
        varios: 'Varios',
        prueba_vacio_motor: 'Prueba de Vacio de Motor',
        inhg: 'InHg',
        video_noconformidad: 'Video de no conformidad',
        analisis_gases: 'Análisis de Gases',
        co: 'CO%',
        hc: 'HC ppm',
        co2: 'CO2%',
        o2: 'O2%',
        _2500_300_rpm: '2500/300&nbsp;RPM',
        sistema_refrigeracion: 'Sistema de Refrigeración',
        existe_fugas_radiador: 'Existen fugas de refrigerante  por el radiador<br/><br/>',
        existe_fugas_mangueras: 'Existen fugas de refrigerante por las mangueras de refrigeracion',
        indicador_temperatura_panel: 'Funcionamiento indicador (Testigo) de temperatura en el panel de instrumentos',
        ciclado_electroventilador: 'Ciclado de funcionamiento del electroventilador',
        nivel_refrigerante_motor: 'Nivel de refrigerante de motor',
        sistema_lubricacion: 'Sistema de Lubricación',
        fuga_aceite_sellos: 'Fuga de aceite por retenedores o sellos',
        fuga_aceite_carter: 'Fuga de aceite por empaque de carter',
        fuga_aceite_valvulas: 'Fuga de aceite por empaque tapa valvulas',
        estado_nivel_aceite: 'Estado del indicador nivel de aceite en el panel de instrumentos',
        nivel_aceite_motor: 'Nivel de aceite de motor<br/><br/>',
        sistema_electronico_combustible: 'Sistema electrónico de combustile (Lectura de datos desde el Scanner Automotriz)',
        stftb1: 'STFT&nbsp;B1',
        ltftb1: 'LTFT&nbsp;B1',
        porcentaje_abr: '%',
        valvula_egr: 'Válvula EGR',
        valvula_iac: 'Válvula IAC',
        sensor_thwect:'Sensor THW/ECT',
        sensor_presion: 'Sensor de presión (Baro Pressure)',
        codigo_falla: 'Códigos de falla actuales y almacenados',
        sensor_iat: 'Sensor IAT ',
        ignition_voltage:'Ignition Voltage',
        sensor_ckp: 'Sensor CKP',
        sensor_cmp:'Sensor CMP',
        sensor_map: 'Sensor MAP',
        motor_ralenti_map: 'Motor en ralenti del sensor MAP',
        sensor_tps:'Sensor TPS',
        ancho_puelo_inyectores:'Ancho de pulso de inyectores',
        sensor_o2_s1b1:'Sensor O2 S1B1',
        sensor_o2_s1b2:'Sensor O2 S1B2',
        angulo_avance_ralenti:'Angulo de avance en ralenti',
        angulo_avance_2500_rpm:'Angulo de avance 2500 rpm',
        resistencia_interna_bujias:'Resistencia interna de las bujías',
        codigo_bujias:'Código de las bujías (Las 4 bujías deberan ser iguales)',
        estado_amortiguadores_trasetros:'Estado de amortiguadores traseros',
        prueba_compresion_motor: 'Prueba de compresión de motor',
        ciclindro1: 'Cilindro 1',
        ciclindro2: 'Cilindro 2',
        ciclindro3: 'Cilindro 3',
        ciclindro4: 'Cilindro 4',
        psi: 'psi'
    },
    msn: {
        login_ok: 'Ingreso correctamente.',
        login_fail: 'Error con el usuario o contraseña.',
        msn_sys: 'Aviso del sistema:',
        msn_logout: '¿Desea salir: ',
        msn_seguridad_logout: 'Para mayor segurdad cierre el navegador.',
        save_ok: 'Los datos se grabaron correctamente.',
        edit_ok: 'Los datos se actualizaron correctamente.',
        delete_ok: 'Registro(s) se eliminó correctamente.',
        you_sure_delete: '¿Está seguro de eliminar el registro?',
        menu_exist: 'Descripción de menú ya existe.',
        alias_exist: 'Alias ya existe.',
        ajax_exist: 'Ajax ya existe.',
        boton_exist: 'Boton ya existe.',
        rol_exist: 'Rol ya existe.',
        copy_ok: 'Registro se duplico correctamente.',
        validate: 'Revise los campos marcados',
        propietario_exist: 'Propietario ya existe.',
        upload_ok: 'Archivo se cargo correctamente.',
        aprobar: '¿Está seguro de aprobar el registro?',
        rechazar: '¿Está seguro de rechazar el registro?',
        operacion_ok: 'La operación se realizó correctamente.'
    }
};