<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
    <head>
        <title>VERIFYGAS</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div style="background: #81BEF7;width: 80%;position: relative;margin: auto;padding: 0 20px 0 20px">
            <table style="width: 70%;background: #fff" align="center">
                <tr>
                <td>
                    <img src="http://app.verifygaspacifico.com/public/theme/default/img/logo-pale.png">
                </td>
                <td><b>PRECONVERSION APROBADA POR TALLER</b></td>
                </tr>
                <tr>
                <td colspan="2">
                    <p>Hola, te informamos que se aprobó una pre conversión.</p>
                    
                    <table>
                        <tr>
                        <td>Propietario:</td>
                        <td><b>{NOMBRES}</b></td>
                        </tr>
                        <tr>
                        <td>Placa:</td>
                        <td><b>{PLACA}</b></td>
                        </tr>
                        <tr>
                        <td>Marca:</td>
                        <td><b>{MARCA}</b></td>
                        </tr>
                        <tr>
                        <td>Modelo:</td>
                        <td><b>{MODELO}</b></td>
                        </tr>
                        <tr>
                        <td>Serie:</td>
                        <td><b>{SERIE}</b></td>
                        </tr>
                    </table>
                    <p>Ingrese al sistema y diríjase a: Conversión -> Registros -> Vehículos</p>
                    <p>Para ingresar al sistema de click <a href="http://www.app.verifygaspacifico.com" target="_blank">aqui</a></p>
                </td>
                </tr>
            </table>
        </div>
        <hr>
    </body>
</html>
