var lang_ES = {
    etiquet: {
        option_ap: 'Opciones de Apariencia',
        cerrar_session: 'Cerrar sesión',
        pantalla_full: 'Maximizar pantalla',
        atajo: 'Atajo',
        proyectos: 'Proyectos',
        proyecto_recuentes: 'Proyectos recientes',
        encabezado_fijo: 'Encabezado Fijo',
        menu_fijo: 'Menú Fijo',
        navegacion_fijo: 'Navegación Fijo',
        footer_fijo: 'Footer Fijo',
        contenido_centrado: 'Contenido Centrado',
        menu_derecha: 'Menú a la <b>Derecha</b>',
        menu_arriba: 'Menú <b>Arriba</b>',
        para_daltonicos: 'Para daltónicos',
        estilos: 'Estilos',
        defecto: 'Defecto',
        oscuro_elegante: 'Oscuro Elegante',
        ultra_claro: 'Ultra Claro',
        anaranjado: 'Anaranjado',
        pixel: 'Pixel',
        trasparente: 'Trasparente',
        celeste: 'Celeste',
        user: 'Usuario',
        pass: 'Contraseña',
        forgot_pass: '¿Olvide mi contraseña?',
        copy_right: '&COPY; 2017 -  Perú. Todos los derechos reservados.',
        btn_entrar: 'Entrar',
        search_menu: 'Buscar menú...',
        inactividad: 'Como ha estado inactivo, su sesión está a punto de caducar.',
        tiempo_inactividad: 'Tiempo restante',
        continuar: 'Continuar',
        salir: 'Salir',
        cierre_sesion: 'Advertencia de cierre de sesión',
        loading: 'Cargando...',
        new_menu: 'Nuevo Menú',
        edit_menu: 'Editar Menú',
        descripcion: 'Descripción',
        press_enter: 'Escriba y presione [Enter]',
        t_alias: 'Este alias se utilizará como prefijo para todos los elementos que serán contenidos en el menú que se creará, debe ser único en el sistema y debe finalizar con dos guiones bajo(__). Se permiten 10 caracteres como máximo.',
        t_ajax: `Evento que se ejecutará al dar click en la opción de menú. Ejm: Exe.load('MODULO','OPCION');`,
        alias: 'Alias',
        ajax: 'Ajax',
        activo: 'Activo',
        btn_close: 'Cerrar',
        btn_agregar: 'Agregar',
        btn_limpiar: 'Limpiar',
        icono: 'Icono',
        css: 'Css',
        new_boton: 'Nuevo Botón',
        edit_boton: 'Editar Botón',
        nombres: 'Nombres',
        theme: 'Diseño',
        estado: 'Estado',
        ant: 'Ant',
        sig: 'Sig',
        fin: 'Finalizar',
        tour: 'Tour',
        e_si: 'Si',
        e_no: 'No',
        new_rol: 'Nuevo Rol',
        edit_rol: 'Editar Rol',
        rol_access: 'Accesos para: <span></span>',
        search_sensitive: 'Escriba para buscar...',
        rol: 'Rol',
        preview: 'Vista Previa',
        new_module: 'Nuevo Módulo',
        new_option: 'Nueva Opción',
        new_component: 'Nuevo Componente',
        tipo: 'Tipo',
        crud: 'CRUD',
        seleccionar: 'Seleccionar',
        form: 'Formlulario',
        grid: 'Data Grid',
        fields: 'Campos',
        propierties: 'Propiedades',
        without_title: 'Sin Título',
        grag_element: 'Arrastre los campos desde el panel izquierdo y suéltelos aquí para agregarlos a su formulario.',
        start_building: 'Comienza a Construir',
        title: 'Título',
        note_etiquet: 'Ingrese una etiqueta y presione enter; estas etiquetas se cargan desde lang_ES.js',
        onsubmit: 'OnSubmit',
        note_onsubmit: 'Ingrese el ajax que se ejecutará. Ejemplo: Obj.Namespace.ModuloAx.postNew',
        id: 'Id',
        text: 'Text',
        textarea: 'Textarea',
        checkbox: 'Checkbox',
        radio: 'Radio',
        select: 'Select',
        chk_1: 'Checkbox 1',
        chk_2: 'Checkbox 2',
        chk_3: 'Checkbox 3',
        rd_1: 'Radio 1',
        rd_2: 'Radio 2',
        rd_3: 'Radio 3',
        etiquet: 'Etiqueta',
        field: 'Campo',
        width: 'Ancho',
        placeholder: 'Placeholder',
        no_placeholder: '- Sin placeholder -',
        id_name: 'Id - Name',
        validaciones: 'Validaciones',
        required: 'Required',
        email: 'Email',
        url: 'Url',
        date: 'Date',
        number: 'Number',
        maxlength: 'Maxlength',
        minlength: 'Minlength',
        rangelength: 'Rangelength',
        range: 'Range',
        max: 'Max',
        min: 'Min',
        no_element_selected: 'No hay campos seleccionados',
        select_element: 'Haz clic en un campo en el formulario a la derecha para cambiar sus propiedades.',
        options:'Opciones',
        no_etiqueta: 'Sin etiqueta'
    },
    msn: {
        login_ok: 'Ingreso correctamente.',
        login_fail: 'Error con el usuario o contraseña.',
        msn_sys: 'Aviso del sistema:',
        msn_logout: '¿Desea salir: ',
        msn_seguridad_logout: 'Para mayor segurdad cierre el navegador.',
        save_ok: 'Datos se grabaron correctamente.',
        edit_ok: 'Datos se editaron correctamente.',
        delete_ok: 'Carpeta se eliminó correctamente.',
        you_sure_delete: 'Se eliminarán las subcarptetas y todos los archivos .js ¿Está seguro de eliminar carpeta?',
        menu_exist: 'Descripción de menú ya existe.',
        alias_exist: 'Alias ya existe.',
        ajax_exist: 'Ajax ya existe.',
        boton_exist: 'Boton ya existe.',
        rol_exist: 'Rol ya existe.',
        copy_ok: 'Registro se duplico correctamente.',
        folder_ok: 'Carpeta se creo correctamente.',
        folder_exist: 'Carpeta ya existe.',
        error_system: 'Ocurrió un error inesperado, comuníquese con el Administrador del Sistema.',
        validate: 'Revise los campos marcados'
    }
};