var lang_EN = {
    etiquet: {
        option_ap: 'Appearance Options',
        cerrar_session: 'Sign Out',
        pantalla_full: 'Full Screen',
        atajo: 'Shortcut',
        proyectos: 'Projects',
        proyecto_recuentes: 'Recent projects',
        encabezado_fijo: 'Fixed Header',
        menu_fijo: 'Fixed Navigation',
        navegacion_fijo: 'Fixed Ribbon',
        footer_fijo: 'Fixed Footer',
        contenido_centrado: 'Inside <b>.container</b>',
        menu_derecha: 'RTL Support',
        menu_arriba: 'Menu on <b>top</b>',
        para_daltonicos: 'For Colorblind',
        reset_options: 'Reset options',
        reset_theme: 'Reseat appearance',
        estilos: 'Styles',
        defecto: 'Default',
        oscuro_elegante: 'Dark Elegance',
        ultra_claro: 'Ultra Light',
        anaranjado: 'Orange',
        pixel: 'Pixel',
        trasparente: 'Trasparent',
        celeste: 'Light Blue',
        user: 'Usuario',
        pass: 'Contraseña',
        forgot_pass: '¿Olvide mi contraseña?',
        copy_right: '&COPY; 2017 -  Perú. Todos los derechos reservados.',
        btn_entrar: 'Entrar'
    },
    msn: {
        login_ok: 'Ingreso correctamente.',
        login_fail: 'Error con el usuario o contraseña.',
        msn_sys: 'Aviso del sistema:',
        msn_logout: '¿Desea salir: ',
        msn_seguridad_logout: 'Para mayor segurdad cierre el navegador.',
        save_ok: 'Datos se grabaron correctamente.',
        edit_ok: 'Datos se editaron correctamente.',
        delete_ok: 'Registro(s) se eliminó correctamente.',
        you_sure_delete: '¿Está seguro de eliminar el registro?',
    }
};